version: '3.7'

services:
  tsx-cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    container_name: talebygale-cron
    expose:
      - 3000
    ports:
      - '3000:3000'
    command: node dist/index.js